[package]
name = "rust-day"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="activity"
path="src/lib/activitylib.rs"

[dependencies]
colored = "2.0.0"
crossbeam-channel = "0.5.7"
